services:
  app:
    container_name: git_search_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - .:/var/www/html
    ports:
      - '9000:9000'
    depends_on:
      - mysql
    networks:
      - git-search

  mysql:
    container_name: git_search_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    networks:
      - git-search

  nginx:
    container_name: git_search_nginx
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.git-search.rule=Host(`test.local`)"
      - "traefik.http.routers.git-search.entrypoints=web"
      - "traefik.http.routers.git-search-secure.rule=Host(`test.adicio.hr`)"
      - "traefik.http.routers.git-search-secure.entrypoints=web-secure"
      - "traefik.http.routers.git-search-secure.tls=true"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - mysql
    networks:
      - proxy
      - git-search

volumes:
  db_data:
    driver: local

networks:
  proxy:
    external: true
  git-search: